import assert from 'node:assert/strict';
import { parseSettings, defaultSettings, checkSetting, cvarCommands, hudStyle, serializeSettings } from '/Users/wcarasas/Repos/Walcc.CounterStrike/src/client/src/settings/schema.ts';
const d = defaultSettings();
console.log(cvarCommands(d), hudStyle(d));
assert.deepEqual(parseSettings(null), d);
assert.deepEqual(parseSettings('garbage'), d);
assert.deepEqual(parseSettings('[1]'), d);
assert.deepEqual(parseSettings('null'), d);
const p = parseSettings(JSON.stringify({ sensitivity: 2.5, volume: 33, hudScale: 500, crosshairColor: 'pink', crosshairSize: 'large', crosshairDynamic: 'yes', old: 1, crosshairTranslucent: false }));
assert.equal(p.sensitivity, 2.5); assert.equal(p.volume, 70); assert.equal(p.hudScale, 100);
assert.equal(p.crosshairColor, 'green'); assert.equal(p.crosshairSize, 'large'); assert.equal(p.crosshairDynamic, true); assert.equal(p.crosshairTranslucent, false);
assert.equal((p as any).old, undefined);
assert.equal(checkSetting('sensitivity', 0.30000000000000004), 0.3);
assert.equal(checkSetting('sensitivity', 0.05), undefined);
assert.equal(checkSetting('sensitivity', 20), 20);
assert.equal(checkSetting('sensitivity', 20.1), undefined);
assert.equal(checkSetting('sensitivity', 3.33), undefined);
assert.equal(checkSetting('sensitivity', NaN), undefined);
assert.equal(checkSetting('sensitivity', '3'), undefined);
assert.equal(checkSetting('volume', 0), 0);
assert.equal(checkSetting('crosshairColor', '__proto__'), undefined);
for (let i = 1; i <= 200; i++) assert.equal(checkSetting('sensitivity', Number((i / 10).toFixed(1))), Number((i/10).toFixed(1)));
const all = cvarCommands({ ...d, sensitivity: 20, volume: 100, crosshairColor: 'cyan', crosshairSize: 'small', crosshairTranslucent: false, crosshairDynamic: false });
console.log(all);
assert.throws(() => cvarCommands({ ...d, sensitivity: 99 }));
assert.throws(() => cvarCommands({ ...d, crosshairSize: 'x;quit' as any }));
assert.deepEqual(parseSettings(serializeSettings(p)), p);
console.log('ok');
