import { inviteLink, hasJoinParam, withoutJoinParam, joinAction } from '../../src/client/src/invite/link.ts';
const ok = (cond: boolean, m: string) => { if (!cond) { console.log('FAIL', m); process.exitCode = 1; } };
ok(inviteLink('http://1.2.3.4:27016', '/') === 'http://1.2.3.4:27016/?join=1', 'link root ' + inviteLink('http://1.2.3.4:27016', '/'));
ok(inviteLink('https://cs.example', '/play/index.html') === 'https://cs.example/play/index.html?join=1', 'link path');
ok(inviteLink('https://cs.example', '') === 'https://cs.example/?join=1', 'link empty path');
ok(hasJoinParam('?join=1') && hasJoinParam('?a=b&join=1') && hasJoinParam('join=1'), 'join yes');
ok(!hasJoinParam('') && !hasJoinParam('?join=0') && !hasJoinParam('?join') && !hasJoinParam('?join=true') && !hasJoinParam('?xjoin=1'), 'join no');
ok(withoutJoinParam('http://h/?join=1') === '/', 'clean only ' + withoutJoinParam('http://h/?join=1'));
ok(withoutJoinParam('http://h/p?a=1&join=1&b=2#x') === '/p?a=1&b=2#x', 'clean keeps others ' + withoutJoinParam('http://h/p?a=1&join=1&b=2#x'));
ok(withoutJoinParam('http://h/?join=0') === '/', 'clean any value');
ok(withoutJoinParam('http://h/?a=1') === undefined && withoutJoinParam('http://h/') === undefined, 'nothing to clean');
ok(withoutJoinParam('not a url') === undefined, 'bad href');
ok(joinAction(false, 'Bob') === 'none' && joinAction(false, '') === 'none', 'no join');
ok(joinAction(true, 'Bob') === 'connect', 'connect');
ok(joinAction(true, '') === 'ask-name' && joinAction(true, '   ') === 'ask-name', 'ask name');
console.log('done');
